"""Seed Sovereign Guard DB with demo users and posts."""
import sys, time
sys.path.insert(0, '.')

import models, key_manager
from crypto import rsa, ecc
from crypto.hash_password import hash_password
from crypto.totp import generate_totp_secret
from crypto.sha256 import sha256_hex

models.init_db()

USERS = [
    ("alice",   "alice@securelab.io",  "+1 555 0101", "Alice2026!",   "admin"),
    ("bob",     "bob@securelab.io",    "+1 555 0102", "Bob@Secure99",  "user"),
    ("charlie", "charlie@example.com", "+1 555 0103", "Charlie!Pass1", "user"),
]

POSTS = [
    ("alice", "Welcome to Sovereign Guard",
     "This platform encrypts every post with ECC P-256 ECIES before storing it in the database. Even if someone reads the raw DB, they only see ciphertext."),
    ("alice", "How RSA-2048 Protects Your Profile",
     "Your username, email and phone are each encrypted with your personal RSA-2048 public key using OAEP padding. The private key is wrapped with a master-derived key."),
    ("bob",  "HMAC-SHA256 Integrity Tags",
     "Every record in the database has an HMAC-SHA256 tag. If a single byte is changed outside the app, the integrity check fails and the UI shows a tamper warning."),
    ("bob",  "TOTP Two-Factor Authentication",
     "Login requires a TOTP code generated by HMAC-SHA1 over a time counter — implemented from scratch, compatible with Google Authenticator."),
    ("charlie", "Key Rotation in Action",
     "Admins can rotate any user's RSA and ECC keys. The system re-encrypts all their profile data and posts automatically — zero downtime."),
    ("charlie", "Role-Based Access Control",
     "Admin users can view all accounts, audit logs, and the key management dashboard. Regular users only see the feed and their own profile."),
]

uid_map = {}
for uname, email, phone, password, role in USERS:
    uname_hash = sha256_hex(uname.lower().encode())
    if models.get_user_by_username_hash(uname_hash):
        print(f"  skip {uname} (exists)")
        row = next(u for u in models.get_all_users()
                   if u['username_hash'] == uname_hash)
        uid_map[uname] = row
        continue
    pw_hash, salt = hash_password(password)
    rsa_keys = key_manager.generate_rsa_keys(pw_hash)
    ecc_keys = key_manager.generate_ecc_keys(pw_hash)
    rsa_pub  = (int(rsa_keys['rsa_pub_e'], 16), int(rsa_keys['rsa_pub_n'], 16))
    ecc_pub  = ecc.Point(int(ecc_keys['ecc_pub_x'], 16), int(ecc_keys['ecc_pub_y'], 16))
    username_enc = rsa.encrypt(uname.encode(), rsa_pub).hex()
    email_enc    = rsa.encrypt(email.encode(), rsa_pub).hex()
    phone_enc    = rsa.encrypt(phone.encode(), rsa_pub).hex()
    totp_secret  = generate_totp_secret()
    hmac_tag     = key_manager.compute_user_hmac(0, username_enc, email_enc)
    uid = models.create_user({
        'username_enc': username_enc, 'email_enc': email_enc,
        'phone_enc': phone_enc, 'username_hash': uname_hash,
        'password_hash': pw_hash, 'salt': salt,
        **rsa_keys, **ecc_keys,
        'role': role, 'totp_secret': totp_secret,
        'totp_enabled': 1, 'hmac_tag': hmac_tag,
        'created_at': time.time(),
    })
    real_hmac = key_manager.compute_user_hmac(uid, username_enc, email_enc)
    models.update_user_profile(uid, username_enc, email_enc, phone_enc, uname_hash, real_hmac)
    models.log_action(uid, 'REGISTER', f'role={role} (seeded)', '127.0.0.1')
    print(f"  created {uname} (id={uid}, role={role})")
    uid_map[uname] = models.get_user_by_id(uid)

for author, title, content in POSTS:
    u = uid_map.get(author)
    if not u:
        continue
    ecc_pub = key_manager.get_ecc_public_key(u)
    title_enc   = ecc.encrypt(title.encode(), ecc_pub).hex()
    content_enc = ecc.encrypt(content.encode(), ecc_pub).hex()
    hmac_tag    = key_manager.compute_post_hmac(str(u['id']), title_enc, content_enc)
    now = time.time()
    pid = models.create_post({
        'user_id': u['id'], 'title_enc': title_enc,
        'content_enc': content_enc, 'hmac_tag': hmac_tag,
        'created_at': now, 'updated_at': now,
    })
    print(f"  post {pid!r}: {title[:40]}")

print("\nDB seeded. Login credentials:")
for uname, _, _, pw, role in USERS:
    print(f"  {uname} / {pw}  [{role}]")
print("TOTP code shown on login page (demo mode).")
